import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import { PdfUtil } from 'src/shared/utils/pdf.util';
import { Util } from 'src/shared/utils/util';
import { IpLog } from 'src/shared/models/ip-log/ip-log.entity';
import { Transaction } from 'src/subdomains/supporting/payment/entities/transaction.entity';
import { KycStep } from '../kyc/entities/kyc-step.entity';
import { KycStepName } from '../kyc/enums/kyc-step-name.enum';
import { UserData } from '../user/models/user-data/user-data.entity';
import { ComplianceDecision, GenerateOnboardingPdfDto } from './dto/onboarding-pdf.dto';
import { TransactionSupportInfo } from './dto/user-data-support.dto';

@Injectable()
export class SupportPdfService {
  generateIpLogPdf(userDataId: number, ipLogs: IpLog[]): Promise<string> {
    return new Promise<string>((resolve, reject) => {
      try {
        const pdf = new PDFDocument({ size: 'A4', margin: 50 });
        const chunks: Buffer[] = [];

        pdf.on('data', (chunk) => chunks.push(chunk));
        pdf.on('end', () => resolve(Buffer.concat(chunks).toString('base64')));

        PdfUtil.drawLogo(pdf);

        // Header
        const marginX = 50;
        pdf.moveDown(2);
        pdf.fontSize(18).font('Helvetica-Bold').fillColor('#072440');
        pdf.text('IP Log Report', marginX);
        pdf.moveDown(0.5);
        pdf.fontSize(10).font('Helvetica').fillColor('#333333');
        pdf.text(`User Data ID: ${userDataId}`, marginX);
        pdf.text(`Date: ${new Date().toISOString().split('T')[0]}`, marginX);
        pdf.text(`Total Entries: ${ipLogs.length}`, marginX);
        pdf.moveDown(1);

        // Table
        this.drawIpLogTable(pdf, ipLogs);

        // Footer
        pdf.moveDown(2);
        pdf.fontSize(8).font('Helvetica').fillColor('#999999');
        pdf.text(`Generated by DFX - ${new Date().toISOString()}`, marginX);

        pdf.end();
      } catch (e) {
        reject(e);
      }
    });
  }

  private drawIpLogTable(pdf: InstanceType<typeof PDFDocument>, ipLogs: IpLog[]): void {
    const marginX = 50;
    const { width } = pdf.page;
    const tableWidth = width - marginX * 2;

    const cols = [
      { header: 'Date', width: tableWidth * 0.2 },
      { header: 'IP', width: tableWidth * 0.2 },
      { header: 'Country', width: tableWidth * 0.12 },
      { header: 'Endpoint', width: tableWidth * 0.36 },
      { header: 'Status', width: tableWidth * 0.12 },
    ];

    let y = pdf.y;

    // Headers
    pdf.fontSize(10).font('Helvetica-Bold').fillColor('#072440');
    let x = marginX;
    for (const col of cols) {
      pdf.text(col.header, x, y, { width: col.width - 5 });
      x += col.width;
    }

    y += 18;
    pdf
      .moveTo(marginX, y)
      .lineTo(width - marginX, y)
      .stroke('#CCCCCC');
    y += 8;

    // Rows
    pdf.fontSize(9).font('Helvetica').fillColor('#333333');

    if (ipLogs.length === 0) {
      pdf.text('No IP logs found', marginX, y);
    } else {
      for (const log of ipLogs) {
        if (y > pdf.page.height - 80) {
          pdf.addPage();
          y = 50;
        }

        x = marginX;
        const date = log.created ? new Date(log.created).toISOString().replace('T', ' ').substring(0, 19) : '-';
        const endpoint = log.url?.replace('/v1/', '') ?? '-';

        pdf.fillColor('#333333');
        pdf.text(date, x, y, { width: cols[0].width - 5 });
        x += cols[0].width;
        pdf.text(log.ip ?? '-', x, y, { width: cols[1].width - 5 });
        x += cols[1].width;
        pdf.text(log.country ?? '-', x, y, { width: cols[2].width - 5 });
        x += cols[2].width;
        pdf.text(endpoint, x, y, { width: cols[3].width - 5 });
        x += cols[3].width;

        pdf.fillColor(log.result ? '#28a745' : '#dc3545');
        pdf.text(log.result ? 'Pass' : 'Fail', x, y, { width: cols[4].width - 5 });

        y += 20;
      }
    }

    pdf
      .moveTo(marginX, y)
      .lineTo(width - marginX, y)
      .stroke('#CCCCCC');
    pdf.y = y + 10;
  }

  generateTransactionPdf(
    userDataId: number,
    transactions: Transaction[],
    toTransactionSupportInfo: (tx: Transaction) => TransactionSupportInfo,
  ): Promise<string> {
    return new Promise<string>((resolve, reject) => {
      try {
        const pdf = new PDFDocument({ size: 'A4', layout: 'landscape', margin: 40 });
        const chunks: Buffer[] = [];

        pdf.on('data', (chunk) => chunks.push(chunk));
        pdf.on('end', () => resolve(Buffer.concat(chunks).toString('base64')));

        PdfUtil.drawLogo(pdf);

        // Header
        const marginX = 40;
        pdf.moveDown(2);
        pdf.fontSize(18).font('Helvetica-Bold').fillColor('#072440');
        pdf.text('Transaction Report', marginX);
        pdf.moveDown(0.5);
        pdf.fontSize(10).font('Helvetica').fillColor('#333333');
        pdf.text(`User Data ID: ${userDataId}`, marginX);
        pdf.text(`Date: ${new Date().toISOString().split('T')[0]}`, marginX);
        pdf.text(`Total Entries: ${transactions.length}`, marginX);
        pdf.moveDown(1);

        // Table
        this.drawTransactionTable(pdf, transactions, toTransactionSupportInfo);

        // Footer
        pdf.moveDown(2);
        pdf.fontSize(8).font('Helvetica').fillColor('#999999');
        pdf.text(`Generated by DFX - ${new Date().toISOString()}`, marginX);

        pdf.end();
      } catch (e) {
        reject(e);
      }
    });
  }

  private drawTransactionTable(
    pdf: InstanceType<typeof PDFDocument>,
    transactions: Transaction[],
    toTransactionSupportInfo: (tx: Transaction) => TransactionSupportInfo,
  ): void {
    const marginX = 40;
    const { width } = pdf.page;
    const tableWidth = width - marginX * 2;

    const cols = [
      { header: 'ID', width: tableWidth * 0.05 },
      { header: 'UID', width: tableWidth * 0.12 },
      { header: 'Type', width: tableWidth * 0.08 },
      { header: 'Source', width: tableWidth * 0.1 },
      { header: 'Input', width: tableWidth * 0.15 },
      { header: 'CHF', width: tableWidth * 0.1 },
      { header: 'EUR', width: tableWidth * 0.1 },
      { header: 'AML', width: tableWidth * 0.1 },
      { header: 'Chargeback', width: tableWidth * 0.1 },
      { header: 'Created', width: tableWidth * 0.1 },
    ];

    let y = pdf.y;

    // Headers
    pdf.fontSize(8).font('Helvetica-Bold').fillColor('#072440');
    let x = marginX;
    for (const col of cols) {
      pdf.text(col.header, x, y, { width: col.width - 4 });
      x += col.width;
    }

    y += 16;
    pdf
      .moveTo(marginX, y)
      .lineTo(width - marginX, y)
      .stroke('#CCCCCC');
    y += 6;

    // Rows
    pdf.fontSize(7).font('Helvetica').fillColor('#333333');

    if (transactions.length === 0) {
      pdf.text('No transactions found', marginX, y);
    } else {
      for (const tx of transactions) {
        if (y > pdf.page.height - 60) {
          pdf.addPage();
          y = 40;
        }

        const info = toTransactionSupportInfo(tx);
        const date = info.created ? new Date(info.created).toISOString().split('T')[0] : '-';
        const input = info.inputAmount != null ? `${info.inputAmount.toFixed(2)} ${info.inputAsset ?? ''}` : '-';
        const chargeback = info.chargebackDate ? new Date(info.chargebackDate).toISOString().split('T')[0] : '-';

        x = marginX;
        pdf.fillColor('#333333');
        pdf.text(String(info.id), x, y, { width: cols[0].width - 4 });
        x += cols[0].width;
        pdf.text(info.uid ?? '-', x, y, { width: cols[1].width - 4 });
        x += cols[1].width;
        pdf.text(info.type ?? '-', x, y, { width: cols[2].width - 4 });
        x += cols[2].width;
        pdf.text(info.sourceType ?? '-', x, y, { width: cols[3].width - 4 });
        x += cols[3].width;
        pdf.text(input, x, y, { width: cols[4].width - 4 });
        x += cols[4].width;
        pdf.text(info.amountInChf?.toFixed(2) ?? '-', x, y, { width: cols[5].width - 4 });
        x += cols[5].width;
        pdf.text(info.amountInEur?.toFixed(2) ?? '-', x, y, { width: cols[6].width - 4 });
        x += cols[6].width;
        pdf.text(info.amlCheck ?? '-', x, y, { width: cols[7].width - 4 });
        x += cols[7].width;

        if (chargeback !== '-') {
          pdf.fillColor('#dc3545');
        }
        pdf.text(chargeback, x, y, { width: cols[8].width - 4 });
        x += cols[8].width;

        pdf.fillColor('#333333');
        pdf.text(date, x, y, { width: cols[9].width - 4 });

        y += 16;
      }
    }

    pdf
      .moveTo(marginX, y)
      .lineTo(width - marginX, y)
      .stroke('#CCCCCC');
    pdf.y = y + 10;
  }

  createOnboardingPdf(
    userData: UserData,
    kycFiles: { name: string; type: string; subType?: string }[],
    kycSteps: KycStep[],
    dto: GenerateOnboardingPdfDto,
  ): Promise<string> {
    return new Promise<string>((resolve, reject) => {
      try {
        const pdf = new PDFDocument({ size: 'A4', margin: 50 });
        const chunks: Buffer[] = [];

        pdf.on('data', (chunk) => chunks.push(chunk));
        pdf.on('end', () => resolve(Buffer.concat(chunks).toString('base64')));

        PdfUtil.drawLogo(pdf);

        const marginX = 50;
        const { width } = pdf.page;

        // Header
        pdf.moveDown(2);
        pdf.fontSize(18).font('Helvetica-Bold').fillColor('#072440');
        pdf.text('GwG Kunden Onboarding', marginX);
        pdf.moveDown(0.5);
        pdf.fontSize(10).font('Helvetica').fillColor('#333333');
        pdf.text(`UserData ID: ${userData.id}`, marginX);
        pdf.text(`Datum: ${new Date().toISOString().split('T')[0]}`, marginX);
        pdf.moveDown(1);

        // User Data Section
        this.drawOnboardingSectionHeader(pdf, 'Benutzerdaten', marginX);
        this.drawOnboardingField(pdf, 'Account Type', userData.accountType ?? '-', marginX, width);
        this.drawOnboardingField(pdf, 'Name', userData.completeName ?? '-', marginX, width);
        this.drawOnboardingField(
          pdf,
          'Adresse',
          [userData.street, userData.zip, userData.location].filter(Boolean).join(', ') || '-',
          marginX,
          width,
        );
        this.drawOnboardingField(
          pdf,
          'Geburtstag',
          userData.birthday ? new Date(userData.birthday).toLocaleDateString('de-DE') : '-',
          marginX,
          width,
        );
        this.drawOnboardingField(pdf, 'E-Mail', userData.mail ?? '-', marginX, width);
        this.drawOnboardingField(pdf, 'Telefon', userData.phone ?? '-', marginX, width);
        this.drawOnboardingField(pdf, 'Sprache', userData.language?.name ?? '-', marginX, width);
        this.drawOnboardingField(pdf, 'Nationalität', userData.nationality?.name ?? '-', marginX, width);
        this.drawOnboardingField(pdf, 'PEP Status', userData.pep ? 'Ja' : 'Nein', marginX, width);
        this.drawOnboardingField(pdf, 'KYC Hash', userData.kycHash ?? '-', marginX, width);
        this.drawOnboardingField(
          pdf,
          'Account Opener Authorization',
          userData.accountOpenerAuthorization ? 'Ja' : 'Nein',
          marginX,
          width,
        );
        pdf.moveDown(1);

        // Organization Data (if applicable)
        if (userData.organization) {
          this.drawOnboardingSectionHeader(pdf, 'Organisation', marginX);
          this.drawOnboardingField(pdf, 'Name', userData.organizationName ?? '-', marginX, width);
          this.drawOnboardingField(pdf, 'Legal Entity', userData.legalEntity ?? '-', marginX, width);
          this.drawOnboardingField(pdf, 'Signatory Power', userData.signatoryPower ?? '-', marginX, width);

          // Get operational activity from KycStep
          const operationalActivityStep = kycSteps.find((s) => s.name === KycStepName.OPERATIONAL_ACTIVITY);
          if (operationalActivityStep?.result) {
            try {
              const opResult = JSON.parse(operationalActivityStep.result) as Record<string, unknown>;
              this.drawOnboardingField(
                pdf,
                'Operational Activity',
                opResult.isOperational != null ? String(opResult.isOperational) : '-',
                marginX,
                width,
              );
              this.drawOnboardingField(
                pdf,
                'Website',
                opResult.websiteUrl ? String(opResult.websiteUrl) : '-',
                marginX,
                width,
              );
            } catch {
              // ignore parse errors
            }
          }
          pdf.moveDown(1);
        }

        // KycSteps with result data (Financial Data, Beneficial Owners)
        const financialDataStep = kycSteps.find((s) => s.name === KycStepName.FINANCIAL_DATA);
        if (financialDataStep?.result) {
          try {
            const financialData = JSON.parse(financialDataStep.result) as unknown;
            this.drawOnboardingSectionHeader(pdf, 'Financial Data', marginX);
            this.drawOnboardingKeyValueObject(pdf, financialData, marginX, width);
            pdf.moveDown(1);
          } catch {
            // ignore parse errors
          }
        }

        const beneficialOwnerStep = kycSteps.find((s) => s.name === KycStepName.BENEFICIAL_OWNER);
        if (beneficialOwnerStep?.result) {
          try {
            const beneficialData = JSON.parse(beneficialOwnerStep.result) as unknown;
            this.drawOnboardingSectionHeader(pdf, 'Beneficial Owners', marginX);
            this.drawOnboardingKeyValueObject(pdf, beneficialData, marginX, width);
            pdf.moveDown(1);
          } catch {
            // ignore parse errors
          }
        }

        // Documents Section
        this.drawOnboardingSectionHeader(pdf, 'Dokumente', marginX);
        const documentTypes = [
          'Deckblatt',
          'Identifikationsdokument',
          'Formular A',
          'Formular K',
          'Name Checks',
          'Handelsregister',
          'Vollmacht',
          'Aktienbuch',
        ];
        for (const docType of documentTypes) {
          const file = kycFiles.find((f) => f.name.toLowerCase().includes(docType.toLowerCase()));
          this.drawOnboardingField(pdf, docType, file?.name ?? 'nicht vorhanden', marginX, width);
        }
        pdf.moveDown(1);

        // Compliance Fields
        this.drawOnboardingSectionHeader(pdf, 'Compliance Bewertung', marginX);
        this.drawOnboardingField(pdf, 'Complex Org Structure', dto.complexOrgStructure ?? '-', marginX, width);
        this.drawOnboardingField(pdf, 'HighRisk Einstufung', dto.highRisk ?? '-', marginX, width);
        this.drawOnboardingField(pdf, 'Deposit Limit', dto.depositLimit ?? '-', marginX, width);
        this.drawOnboardingField(pdf, 'AML Account Type', dto.amlAccountType ?? '-', marginX, width);
        pdf.moveDown(1);

        // Text Fields
        if (dto.commentGmeR) {
          this.drawOnboardingSectionHeader(pdf, 'Kommentar GmeR', marginX);
          pdf.fontSize(9).font('Helvetica').fillColor('#333333');
          pdf.text(dto.commentGmeR, marginX, pdf.y, { width: width - marginX * 2 });
          pdf.moveDown(1);
        }

        if (dto.reasonSeatingCompany) {
          this.drawOnboardingSectionHeader(pdf, 'Sitzgesellschaft Begründung', marginX);
          pdf.fontSize(9).font('Helvetica').fillColor('#333333');
          pdf.text(dto.reasonSeatingCompany, marginX, pdf.y, { width: width - marginX * 2 });
          pdf.moveDown(1);
        }

        if (dto.businessActivities) {
          this.drawOnboardingSectionHeader(pdf, 'Geschäftliche Aktivitäten', marginX);
          pdf.fontSize(9).font('Helvetica').fillColor('#333333');
          pdf.text(dto.businessActivities, marginX, pdf.y, { width: width - marginX * 2 });
          pdf.moveDown(1);
        }

        // Footer with Final Decision
        pdf.moveDown(2);
        pdf
          .moveTo(marginX, pdf.y)
          .lineTo(width - marginX, pdf.y)
          .stroke('#CCCCCC');
        pdf.moveDown(1);

        pdf.fontSize(12).font('Helvetica-Bold');
        pdf.fillColor(dto.finalDecision === ComplianceDecision.ACCEPTED ? '#28a745' : '#dc3545');
        pdf.text(`Finaler Entscheid: ${dto.finalDecision}`, marginX);
        pdf.moveDown(0.5);

        pdf.fontSize(10).font('Helvetica').fillColor('#333333');
        pdf.text(`Bearbeitet von: ${dto.processedBy}`, marginX);
        pdf.text(`Datum: ${Util.localeDataString(new Date(), 'DE')}`, marginX);

        pdf.moveDown(2);
        pdf.fontSize(8).font('Helvetica').fillColor('#999999');
        pdf.text(`Generated by DFX - ${new Date().toISOString()}`, marginX);

        pdf.end();
      } catch (e) {
        reject(e);
      }
    });
  }

  private drawOnboardingSectionHeader(pdf: InstanceType<typeof PDFDocument>, title: string, marginX: number): void {
    if (pdf.y > pdf.page.height - 100) {
      pdf.addPage();
    }
    pdf.fontSize(12).font('Helvetica-Bold').fillColor('#072440');
    pdf.text(title, marginX);
    pdf.moveDown(0.3);
  }

  private drawOnboardingField(
    pdf: InstanceType<typeof PDFDocument>,
    label: string,
    value: string,
    marginX: number,
    pageWidth: number,
  ): void {
    if (pdf.y > pdf.page.height - 60) {
      pdf.addPage();
    }
    const labelWidth = 180;
    const y = pdf.y;

    pdf.fontSize(9).font('Helvetica-Bold').fillColor('#666666');
    pdf.text(label, marginX, y, { width: labelWidth, continued: false });

    pdf.fontSize(9).font('Helvetica').fillColor('#333333');
    pdf.text(value, marginX + labelWidth, y, { width: pageWidth - marginX * 2 - labelWidth });

    pdf.y = Math.max(pdf.y, y + 14);
  }

  private drawOnboardingKeyValueObject(
    pdf: InstanceType<typeof PDFDocument>,
    data: unknown,
    marginX: number,
    pageWidth: number,
  ): void {
    // Handle array of {key, value} objects (e.g. FinancialData)
    if (Array.isArray(data)) {
      for (const item of data) {
        if (item && typeof item === 'object' && 'key' in item) {
          const key = String((item as { key: unknown }).key);
          const rawValue = (item as { value: unknown }).value;
          const value = this.formatPdfValue(rawValue);
          this.drawOnboardingField(pdf, key, value, marginX, pageWidth);
        }
      }
      return;
    }

    // Handle flat object (e.g. BeneficialOwner)
    if (typeof data === 'object' && data !== null) {
      for (const [key, value] of Object.entries(data as Record<string, unknown>)) {
        if (value === null || value === undefined) continue;
        const displayValue = this.formatPdfValue(value);
        this.drawOnboardingField(pdf, key, displayValue, marginX, pageWidth);
      }
    }
  }

  private formatPdfValue(value: unknown): string {
    if (value === null || value === undefined) return '-';
    // For primitives (string, number, boolean), just convert to string
    if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') {
      return String(value);
    }
    // For everything else (arrays, objects), use JSON.stringify
    try {
      return JSON.stringify(value);
    } catch {
      return '-';
    }
  }
}
