#!/usr/bin/env node

const fs = require('fs');

// verify that no addresses/signatures are commited
const thunderFile = fs.readFileSync('thunder-tests/thunderclient.json');
const thunderRequests = JSON.parse(thunderFile.toString());

const authRequests = thunderRequests.filter((r) => ['Sign In', 'Sign Up'].includes(r.name));
if (authRequests.length != 2) {
  console.error('Not all auth requests (Sign In, Sign Up) found!');
  process.exit(1);
}

for (const r of authRequests) {
  const body = JSON.parse(r.body.raw);
  if (body.address !== 'address' || body.signature !== 'signature') {
    console.error('Non-dummy value found in auth request:', r);
    process.exit(1);
  }
}
