#!/usr/bin/env node

const fs = require('fs');

// verify that no addresses/signatures are committed
const thunderFile = fs.readFileSync('thunder-tests/thunderEnvironment.json');
const thunderEnvironments = JSON.parse(thunderFile.toString());

const prodEnvironments = thunderEnvironments.filter((r) => r.name.includes('prd'));
for (const env of prodEnvironments) {
  const addressField = env.data.find((d) => d.name === 'address');
  const signatureField = env.data.find((d) => d.name === 'signature');
  const tokenField = env.data.find((d) => d.name === 'token');

  if (!addressField || addressField.value || !signatureField || signatureField.value || tokenField?.value) {
    console.error(`Address, signature or token found in ${env.name} environment:`, env);
    process.exit(1);
  }
}
