import { Blockchain } from 'src/integration/blockchain/shared/enums/blockchain.enum';

// --- PROVIDER ENUMS --- //

// Scorechain blockchain identifiers (subset relevant for DFX; full list via GET /blockchains)
export enum ScorechainBlockchain {
  BITCOIN = 'BITCOIN',
  BITCOINCASH = 'BITCOINCASH',
  LITECOIN = 'LITECOIN',
  DOGECOIN = 'DOGECOIN',
  ETHEREUM = 'ETHEREUM',
  ARBITRUMONE = 'ARBITRUMONE',
  OPTIMISM = 'OPTIMISM',
  POLYGON = 'POLYGON',
  BASE = 'BASE',
  BSC = 'BSC',
  SOLANA = 'SOLANA',
  TRON = 'TRON',
  RIPPLE = 'RIPPLE',
  CARDANO = 'CARDANO',
}

export enum ScorechainAnalysisType {
  ASSIGNED = 'ASSIGNED',
  INCOMING = 'INCOMING',
  OUTGOING = 'OUTGOING',
  FULL = 'FULL',
}

export enum ScorechainObjectType {
  ADDRESS = 'ADDRESS',
  TRANSACTION = 'TRANSACTION',
  WALLET = 'WALLET',
}

// Maps the DFX Blockchain enum to Scorechain identifiers. Chains not present here are not
// supported by this integration and are skipped with an explicit not-supported result.
export const ScorechainBlockchainMap: { [b in Blockchain]?: ScorechainBlockchain } = {
  [Blockchain.BITCOIN]: ScorechainBlockchain.BITCOIN,
  [Blockchain.ETHEREUM]: ScorechainBlockchain.ETHEREUM,
  [Blockchain.ARBITRUM]: ScorechainBlockchain.ARBITRUMONE,
  [Blockchain.OPTIMISM]: ScorechainBlockchain.OPTIMISM,
  [Blockchain.POLYGON]: ScorechainBlockchain.POLYGON,
  [Blockchain.BASE]: ScorechainBlockchain.BASE,
  [Blockchain.BINANCE_SMART_CHAIN]: ScorechainBlockchain.BSC,
  [Blockchain.SOLANA]: ScorechainBlockchain.SOLANA,
  [Blockchain.TRON]: ScorechainBlockchain.TRON,
};

export function toScorechainBlockchain(blockchain: Blockchain): ScorechainBlockchain | undefined {
  return ScorechainBlockchainMap[blockchain];
}

// --- REQUESTS --- //

export interface ScoringAnalysisRequest {
  objectType: ScorechainObjectType;
  objectId: string; // address or transaction hash
  blockchain: ScorechainBlockchain;
  analysisType: ScorechainAnalysisType;
  coin?: string; // 'ALL' | 'MAIN' | 'STABLE' | coinChainId
  depth?: number; // <=100 UTXO, <=6 account-based
}

export interface RegisterDepositRequest {
  blockchain: ScorechainBlockchain;
  hash: string;
  depositAddress: string;
  customerRefId?: string;
}

export interface RegisterWithdrawalRequest {
  blockchain: ScorechainBlockchain;
  withdrawAddress: string;
  amount: number;
  coinChainId: string; // token contract or 'MAIN'
  identifier?: string; // tracking UUID; auto-generated by provider if omitted
}

// --- RESPONSES --- //

// Synchronous scoring result. Field names follow the provider OpenAPI; kept permissive
// where the exact schema is not pinned down, with the raw payload persisted for audit.
export interface ScoringAnalysisResponse {
  score?: number;
  severity?: string;
  lowestScore?: number;
  riskIndicators?: unknown;
  [key: string]: unknown;
}

// Async registration ack (provider schema: PendingWithdrawal / deposit feed ack).
export interface PendingTransactionResponse {
  blockchain: ScorechainBlockchain;
  identifier: string;
}

export interface ScorechainPublicKeyResponse {
  publicKeys: string[];
}

// TMS scenario alert (webhook ScenarioAlertCallback / GET /scenarios/{id}/alerts).
export interface ScorechainAlert {
  scenarioId?: string;
  alertId?: string;
  identifier?: string;
  blockchain?: string;
  severity?: string;
  [key: string]: unknown;
}
