// Repo-wide coverage ratchet. Every production file that already reaches 100% on all four
// metrics is pinned here, so a change that drops coverage on any of them fails CI.
//
// This is a REGRESSION gate, not a claim of exhaustive testing: it freezes the coverage that
// exists today. Files not listed here are still uncovered or only partially covered - see
// docs/coverage-gate.md for the measured gaps and for how the list is meant to grow.
//
// Two rules keep the numbers honest:
//   1. Full compilation (tsconfig.coverage.json, isolatedModules: false), same as the Frick gate.
//      The main suite runs ts-jest transpile-only, which emits the emitDecoratorMetadata helpers
//      differently and reports phantom uncovered branches on dependency-injected constructors.
//   2. The whole suite runs, because a file is frequently covered by specs other than its own.
//
// The dedicated Frick gate (jest.frick.config.js) stays separate on purpose: it runs ONLY the
// seven Frick specs and therefore proves that those specs alone reach 100% - an assertion this
// repo-wide run cannot make, because here any spec may contribute the coverage.
const base = require('./package.json').jest;

module.exports = {
  ...base,
  transform: { '^.+\\.(t|j)s$': ['ts-jest', { tsconfig: 'tsconfig.coverage.json' }] },
  collectCoverageFrom: [
    '**/*.ts',
    '!**/*.spec.ts',
    '!**/__tests__/**',
    '!**/__test__/**',
    '!**/tests/**',
    '!**/__mocks__/**',
    '!**/*.mock.ts',
    '!**/*.d.ts',
    '!jest-env.setup.ts',
    // Test scaffolding that lives outside a __tests__ directory: imported only by specs
    // (60 and 28 importers respectively, all of them *.spec.ts). Pinning them would make an
    // untested change to a test helper fail the production gate.
    '!shared/utils/test.util.ts',
    '!shared/utils/test.shared.module.ts',
  ],
  // json-summary is what docs/coverage-gate.md tells you to read when extending the pinned list.
  coverageReporters: ['text-summary', 'json-summary'],
  coverageDirectory: '../coverage-gate',
  coverageThreshold: {
    // --- Files carrying real logic (functions and/or branches) ------------------
    'src/config/frick.config.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/bank/dto/frick-vban.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/bank/dto/frick.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/bank/dto/olkypay.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/bank/dto/yapeal.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/bank/services/frick.service.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/bank/services/iso20022.service.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/binance-pay/dto/binance.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/blockchain/bitcoin/node/bitcoin-client.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/bitcoin/node/rpc/node-not-ready.error.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/bitcoin/services/bitcoin-based-fee.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/boltz/dto/boltz.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/blockchain/monero/dto/monero.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/monero/monero-helper.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/realunit/dto/realunit-broker.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/shared/enums/blockchain.enum.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/shared/errors/tx-broadcast.error.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/shared/evm/paymaster/pimlico-paymaster.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/zano/zano-helper.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/checkout/dto/checkout.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/exchange/dto/mexc.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/exchange/dto/scrypt.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/exchange/dto/trade-result.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/exchange/enums/exchange.enum.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/infrastructure/storage/azure-storage.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/infrastructure/storage/storage.factory.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/infrastructure/storage/storage.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/kucoin-pay/kucoin-pay.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/lightning/dto/lnd.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/scorechain/dto/scorechain-screening-dto.mapper.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/scorechain/exceptions/scorechain-object-not-found.exception.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/sift/dto/sift.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/polyfills.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/shared/auth/allow-tfa-pending.decorator.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/shared/auth/user-role.enum.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/shared/services/typeorm-logger.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/shared/utils/bitbox-ascii.util.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/shared/utils/cron.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/shared/utils/custom-cron-expression.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/shared/utils/request-client.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/shared/validators/is-ssrf-safe-url.validator.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/accounting/controllers/ledger.controller.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/accounting/dto/ledger-account.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/accounting/dto/ledger-dto.mapper.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/accounting/dto/ledger-query.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/accounting/dto/ledger-reconciliation.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/accounting/entities/ledger-account.entity.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/accounting/entities/ledger-leg.entity.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/accounting/entities/ledger-tx.entity.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/accounting/repositories/ledger-account.repository.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/accounting/repositories/ledger-leg.repository.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/accounting/repositories/ledger-tx.repository.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/accounting/services/consumers/ledger-gate-blocked.exception.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/accounting/services/consumers/ledger-mark-bridge.helper.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/accounting/services/ledger-account.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/accounting/services/ledger-booking-job.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/accounting/services/ledger-bootstrap.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/aml/enums/aml-list-status.enum.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/aml/enums/aml-reason.enum.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/subdomains/core/aml/enums/aml-rule.enum.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/subdomains/core/aml/enums/check-status.enum.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/aml/enums/scorechain-outcome.enum.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/aml/services/transaction-aml-check.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/buy-crypto/process/exceptions/abort-batch-creation.exception.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/custody/dto/output/custody-order-history.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/custody/enums/custody.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/subdomains/core/faucet-request/enums/faucet-request.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/history/dto/history.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/subdomains/core/history/dto/output/chain-report-history.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/history/dto/output/coin-tracking-history.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/liquidity-management/enums/index.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/liquidity-management/exceptions/order-failed.exception.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/monitoring/observers/external-services.observer.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/monitoring/observers/realunit-w2w-gas.observer.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/payment-link/entities/payment-link.config.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/payment-link/enums/index.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/subdomains/core/payment-link/enums/merchant.enum.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/trading/enums/index.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/subdomains/generic/forwarding/controllers/lnurld-forward.controller.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/forwarding/controllers/lnurlw-forward.controller.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/gs/middleware/debug-query-tree-size.middleware.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/kyc/dto/ident-result-data.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/kyc/dto/kyc-error.enum.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/subdomains/generic/kyc/dto/kyc-file.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/subdomains/generic/kyc/dto/manual-ident-result.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/kyc/dto/mapper/kyc-file.mapper.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/kyc/dto/output/kyc-info.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/kyc/dto/output/setup-2fa.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/kyc/enums/content-type.enum.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/kyc/enums/file-category.enum.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/kyc/enums/kyc-step-name.enum.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/kyc/enums/review-status.enum.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/support/dto/onboarding-pdf.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/support/dto/user-data-support.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/auth/dto/auth-lnurl.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/bank-data/dto/create-bank-data.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/bank-data/dto/update-bank-data.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/kyc/dto/kyc-file.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/recommendation/dto/recommendation.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/user-data-relation/dto/user-data-relation.enum.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/user-data/account-type.enum.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/user-data/jwt-revocation-sync.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/user-data/kyc-identification-type.enum.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/user-data/user-data.enum.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/user/dto/verify-mail.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/user/user.enum.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/services/webhook/dto/webhook.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/bank-tx/bank-tx/dto/sepa.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/bank-tx/bank-tx/services/bank-tx-frick.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/bank-tx/bank-tx/services/bank-tx-outgoing-match.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/bank/bank/dto/bank.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/bank/virtual-iban/providers/frick-viban.provider.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/bank/virtual-iban/providers/yapeal-viban.provider.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/dex/exceptions/price-slippage.exception.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/dex/strategies/check-liquidity/impl/base/check-liquidity.strategy-registry.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/dex/strategies/purchase-liquidity/impl/base/purchase-liquidity.strategy-registry.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/fiat-output/dto/create-fiat-output.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/fiat-output/dto/update-fiat-output.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/fiat-output/fiat-output-frick.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/log/log.entity.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/subdomains/supporting/notification/enums/index.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payin/strategies/register/impl/base/polling.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payin/strategies/register/impl/base/register.strategy-registry.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payin/strategies/send/impl/base/send.strategy-registry.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payment/dto/payment-method.enum.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payment/dto/transaction-helper/quote-error.enum.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payment/dto/transaction-helper/tx-statement-details.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payment/dto/transaction.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/entities/payout-order.entity.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/exceptions/invalid-payout-amount.exception.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/exceptions/payout-broadcast.exception.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/factories/payout-order.factory.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/repositories/payout-order.repository.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/services/payout-arbitrum.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/services/payout-arkade.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/services/payout-base.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/services/payout-bitcoin-testnet4.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/services/payout-bsc.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/services/payout-citrea.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/services/payout-ethereum.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/services/payout-evm.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/services/payout-firo.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/services/payout-gnosis.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/services/payout-icp.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/services/payout-lightning.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/services/payout-monero.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/services/payout-optimism.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/services/payout-polygon.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/services/payout-sepolia.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/services/payout-spark.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/services/payout-tron.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/services/payout-zano.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/arbitrum-coin.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/arbitrum-token.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/arkade.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/base-coin.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/base-token.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/base/bitcoin-based.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/base/icp.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/base/payout.strategy-registry.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/base/payout.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/base/tron.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/base/zano.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/bitcoin-testnet4.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/bitcoin.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/bsc-coin.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/bsc-token.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/cardano-coin.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/cardano-token.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/citrea-coin.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/citrea-token.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/ethereum-coin.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/ethereum-token.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/firo.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/gnosis-coin.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/gnosis-token.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/icp-coin.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/icp-token.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/lightning.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/monero.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/optimism-coin.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/optimism-token.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/polygon-coin.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/polygon-token.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/sepolia-coin.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/sepolia-token.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/solana-coin.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/solana-token.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/spark.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/tron-coin.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/tron-token.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/zano-coin.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/payout/impl/zano-token.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/prepare/impl/base/evm.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/strategies/prepare/impl/base/prepare.strategy-registry.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/pricing/domain/exceptions/price-invalid.exception.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/pricing/domain/exceptions/price-unavailable.exception.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/pricing/dto/price-request.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/realunit/controllers/realunit-legal.controller.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/realunit/dto/client.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/realunit/dto/realunit-confirm-aktionariat.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/realunit/dto/realunit-legal-dto.mapper.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/realunit/dto/realunit-registration.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/realunit/entities/aktionariat-registration.entity.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/realunit/entities/realunit-legal-acceptance.entity.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/realunit/enums/realunit-legal-agreement.enum.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/realunit/exceptions/buy-exceptions.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/realunit/exceptions/price-source-unavailable.exception.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/realunit/realunit-dev.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/realunit/realunit-legal.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/realunit/repositories/aktionariat-registration.repository.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/realunit/repositories/realunit-legal-acceptance.repository.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/recall/recall-reason.enum.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/support-issue/dto/support-issue.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/support-issue/enums/department.enum.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/support-issue/enums/support-issue.enum.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/support-issue/enums/support-log.enum.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },

    // --- Files that are purely declarative today (no functions, no branches) ----
    // Pinned deliberately: the gate becomes a real guard the moment logic is added to
    // one of them - new code there has to arrive with tests or CI turns red.
    'src/config/chains.config.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/config/config.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/alchemy/alchemy.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/bank/bank.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/binance-pay/binance-pay.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/binance-pay/dto/binance-enum.mapper.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/api/blockchain-api.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/api/dto/create-transaction.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/api/dto/get-balances.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/arbitrum/arbitrum.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/arkade/arkade.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/arweave/arweave.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/base/base.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/blockchain/bitcoin-testnet4/bitcoin-testnet4.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/bitcoin/bitcoin.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/bitcoin/node/dto/command.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/bitcoin/node/rpc/index.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/blockchain.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/blockchain/boltz/boltz.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/blockchain/bsc/bsc.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/blockchain/cardano/cardano.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/citrea/citrea.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/clementine/clementine.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/deuro/deuro.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/blockchain/ebel2x/ebel2x.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/ethereum/ethereum.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/firo/firo.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/blockchain/frankencoin/frankencoin.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/gnosis/gnosis.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/icp/icp.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/blockchain/juice/juice.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/blockchain/monero/monero.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/optimism/optimism.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/polygon/polygon.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/realunit/realunit-blockchain.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/sepolia/sepolia.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/shared/blockscout/blockscout.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/shared/evm/delegation/eip7702-delegation.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/shared/evm/paymaster/pimlico-paymaster.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/shared/util/blockchain.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/solana/solana.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/blockchain/spark/spark.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/blockchain/tron/tron.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/blockchain/zano/zano.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/checkout/checkout.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/exchange/dto/trade-order.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/exchange/dto/withdrawal-order.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/geolocation/geo-location.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/ikna/dto/ikna-query.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/ikna/ikna.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/infrastructure/storage/worm-retention.const.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/integration.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/kucoin-pay/kucoin-pay.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/letter/letter.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/lightning/lightning.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/railgun/railgun.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/scorechain/dto/scorechain-query.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/scorechain/dto/scorechain-screening.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/integration/scorechain/scorechain.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/sift/sift.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/integration/tatum/tatum.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/shared/dto/entity.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/shared/dto/error.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/shared/dto/route.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/shared/models/asset/dto/asset-query.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/shared/models/asset/dto/update-asset.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/shared/models/country/dto/country.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/shared/models/language/dto/language.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/shared/models/language/language.entity.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/shared/models/setting/dto/custom-sign-up-fees.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/shared/models/setting/dto/info-banner.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/shared/models/setting/dto/ip-blacklist.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/shared/models/setting/dto/manual-log-position.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/shared/models/setting/dto/support-clerk-account.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/shared/models/setting/dto/update-process.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/shared/models/setting/setting.entity.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/shared/shared.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/shared/utils/logos/dfx-logo.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/shared/utils/logos/realunit-logo-full.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/subdomains/core/accounting/accounting.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/accounting/dto/ledger-margin.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/aml/dto/manual-aml-check.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/aml/entities/sanction.entity.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/buy-crypto/routes/buy/dto/buy-payment-info.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/buy-crypto/routes/buy/dto/buy-quote.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/buy-crypto/routes/buy/dto/buy.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/buy-crypto/routes/buy/dto/pdf.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/buy-crypto/routes/buy/dto/update-buy.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/buy-crypto/routes/swap/dto/swap-payment-info.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/buy-crypto/routes/swap/dto/swap-quote.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/buy-crypto/routes/swap/dto/swap.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/buy-crypto/routes/swap/dto/update-swap.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/custody/config/order-config.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/custody/dto/input/create-custody-account.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/custody/dto/input/custody-signup.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/custody/dto/input/update-custody-account.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/custody/dto/output/custody-account.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/custody/dto/output/custody-auth.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/custody/dto/output/custody-balance.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/custody/dto/output/custody-order-response.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/custody/dto/output/custody-order.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/history/dto/history-filter.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/history/dto/refund-data.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/liquidity-management/dto/input/liquidity-management-action.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/liquidity-management/dto/input/liquidity-management-request.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/liquidity-management/dto/input/liquidity-management-settings.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/liquidity-management/dto/input/liquidity-management-update.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/liquidity-management/dto/output/liquidity-management-rule-output.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/monitoring/system-state-snapshot.entity.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/payment-link/dto/payment-link-recipient-address.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/payment-link/dto/payment-link.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/payment-link/payment-link-payment.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/referral/process/ref.entity.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/referral/reward/dto/update-ref-reward.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/route/dto/update-route.dto.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/subdomains/core/sell-crypto/route/dto/gasless-transfer.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/sell-crypto/route/dto/sell-payment-info.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/sell-crypto/route/dto/sell-quote.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/sell-crypto/route/dto/sell.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/sell-crypto/route/dto/unsigned-tx.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/core/sell-crypto/route/dto/update-sell.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/kyc/dto/input/kyc-query.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/kyc/dto/input/update-kyc-step.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/kyc/dto/input/update-name-check-log.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/kyc/dto/input/verify-2fa.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/kyc/dto/output/kyc-financial-out.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/kyc/dto/output/kyc-merged.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/kyc/entities/mail-change-log.entity.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/kyc/entities/manual-log.entity.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/kyc/entities/merge-log.entity.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/kyc/entities/risk-status-log.entity.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/kyc/entities/totp-auth-log.entity.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/support/dto/transaction-list-query.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/support/entities/support-issue-template.entity.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/auth/dto/auth-response.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/auth/dto/challenge.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/auth/dto/merge-response.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/auth/dto/sign-message.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/custody-provider/custody-provider.entity.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/custody-provider/dto/custody-provider.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/kyc/dto/kyc-data-transfer.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/kyc/dto/kyc-data.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/kyc/dto/kyc-info.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/user-data-relation/dto/update-user-data-relation.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/user/dto/alby.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/user/dto/api-key.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/user/dto/download-user-data.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/user/dto/linked-user.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/user/dto/update-address.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/user/dto/user-name.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/user/dto/user-profile.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/user/dto/user.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/generic/user/models/wallet/dto/wallet.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/address-pool/deposit/dto/create-deposit.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/address-pool/deposit/dto/deposit.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/bank-tx/bank-tx-return/dto/update-bank-tx-return.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/bank/bank-account/bank-account.entity.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/bank/bank-account/dto/bank-account.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/bank/bank-account/dto/create-bank-account.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/bank/virtual-iban/dto/create-virtual-iban.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/bank/virtual-iban/dto/virtual-iban.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/dex/dex.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/subdomains/supporting/dex/strategies/sell-liquidity/impl/base/evm-coin.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/dex/strategies/sell-liquidity/impl/base/evm-token.strategy.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/log/dto/create-log.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/log/log.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/subdomains/supporting/notification/notification.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/notification/realunit-mail-rules.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payin/interfaces/index.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payin/payin-webhook.module.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payin/services/base/payin-bitcoin-based.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payment/dto/transaction-helper/min-amount.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payment/dto/transaction-helper/structured-error.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/payout/payout.module.ts': { branches: 100, functions: 100, lines: 100, statements: 100 },
    'src/subdomains/supporting/payout/services/base/payout-bitcoin-based.service.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/pricing/dto/price-request-raw.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/realunit/dto/realunit-legal.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/realunit/utils/queries.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/support-issue/dto/bind-escalation-chat.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/support-issue/dto/limit-request.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/support-issue/dto/support-issue-label.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/subdomains/supporting/support-issue/dto/update-support-issue.dto.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
  },
};
