export enum NotificationType {
  MAIL = 'Mail',
}

export enum MailType {
  GENERIC = 'Generic',
  ERROR_MONITORING = 'ErrorMonitoring',
  USER_DEPRECATED = 'UserDeprecated',
  USER_V2 = 'UserV2',
  PERSONAL = 'Personal',
  INTERNAL = 'Internal',
}

export enum MailContext {
  BUY_CRYPTO = 'BuyCrypto',
  BUY_CRYPTO_PENDING = 'BuyCryptoPending',
  BUY_CRYPTO_RETURN = 'BuyCryptoReturn',
  BUY_CRYPTO_COMPLETED = 'BuyCryptoCompleted',
  BUY_CRYPTO_PROCESSING = 'BuyCryptoProcessing',
  BUY_CRYPTO_CHARGEBACK_UNCONFIRMED = 'BuyCryptoChargebackUnconfirmed',
  BUY_FIAT = 'BuyFiat',
  BUY_FIAT_PENDING = 'BuyFiatPending',
  BUY_FIAT_RETURN = 'BuyFiatReturn',
  BUY_FIAT_COMPLETED = 'BuyFiatCompleted',
  BUY_FIAT_PROCESSING = 'BuyFiatProcessing',
  CRYPTO_INPUT_RETURN = 'CryptoInputReturn',
  BUY_FIAT_CHARGEBACK_UNCONFIRMED = 'BuyFiatChargebackUnconfirmed',
  CHECKOUT_TX = 'CheckoutTx',
  SEPA = 'SEPA',
  WEBHOOK = 'Webhook',
  BLACK_SQUAD = 'BlackSquad',
  CHANGED_MAIL = 'ChangedMail',
  ADDED_ADDRESS = 'AddedAddress',
  ACCOUNT_MERGE_REQUEST = 'AccountMergeRequest',
  LOGIN = 'Login',
  LIMIT_REQUEST = 'LimitRequest',
  KYC_CHANGED = 'KycChanged',
  KYC_FAILED = 'KycFailed',
  KYC_REMINDER = 'KycReminder',
  CUSTOM = 'Custom',
  REF_REWARD = 'RefReward',
  MONITORING = 'Monitoring',
  DEX = 'Dex',
  PAYOUT = 'Payout',
  PRICING = 'Pricing',
  LIQUIDITY_MANAGEMENT = 'LiquidityManagement',
  UNASSIGNED_TX = 'UnassignedTx',
  SUPPORT_MESSAGE = 'SupportMessage',
  VERIFICATION_MAIL = 'VerificationMail',
  EMAIL_VERIFICATION = 'EmailVerification',
}
