export enum NotificationType {
  MAIL = 'Mail',
}

export enum MailType {
  GENERIC = 'Generic',
  ERROR_MONITORING = 'ErrorMonitoring',
  USER_DEPRECATED = 'UserDeprecated',
  USER_V2 = 'UserV2',
  PERSONAL = 'Personal',
  INTERNAL = 'Internal',
}

export enum MailContext {
  BUY_CRYPTO = 'BuyCrypto',
  BUY_CRYPTO_PENDING = 'BuyCryptoPending',
  BUY_CRYPTO_RETURN = 'BuyCryptoReturn',
  BUY_CRYPTO_COMPLETED = 'BuyCryptoCompleted',
  BUY_CRYPTO_PROCESSING = 'BuyCryptoProcessing',
  BUY_CRYPTO_CHARGEBACK_UNCONFIRMED = 'BuyCryptoChargebackUnconfirmed',
  BUY_FIAT = 'BuyFiat',
  BUY_FIAT_PENDING = 'BuyFiatPending',
  BUY_FIAT_RETURN = 'BuyFiatReturn',
  BUY_FIAT_COMPLETED = 'BuyFiatCompleted',
  BUY_FIAT_PROCESSING = 'BuyFiatProcessing',
  CRYPTO_INPUT_RETURN = 'CryptoInputReturn',
  BUY_FIAT_CHARGEBACK_UNCONFIRMED = 'BuyFiatChargebackUnconfirmed',
  CHECKOUT_TX = 'CheckoutTx',
  SEPA = 'SEPA',
  WEBHOOK = 'Webhook',
  BLACK_SQUAD = 'BlackSquad',
  CHANGED_MAIL = 'ChangedMail',
  ADDED_ADDRESS = 'AddedAddress',
  ACCOUNT_MERGE_REQUEST = 'AccountMergeRequest',
  LOGIN = 'Login',
  LIMIT_REQUEST = 'LimitRequest',
  KYC_CHANGED = 'KycChanged',
  KYC_FAILED = 'KycFailed',
  KYC_MISSING_DATA = 'KycMissingData',
  KYC_REMINDER = 'KycReminder',
  KYC_PAYMENT_DATA = 'KycPaymentData',
  CUSTOM = 'Custom',
  REF_REWARD = 'RefReward',
  MONITORING = 'Monitoring',
  DEX = 'Dex',
  PAYOUT = 'Payout',
  PRICING = 'Pricing',
  LIQUIDITY_MANAGEMENT = 'LiquidityManagement',
  UNASSIGNED_TX = 'UnassignedTx',
  SUPPORT_MESSAGE = 'SupportMessage',
  VERIFICATION_MAIL = 'VerificationMail',
  EMAIL_VERIFICATION = 'EmailVerification',
}

export enum MailContextType {
  BUY_CRYPTO = 'BuyCrypto',
  BUY_FIAT = 'BuyFiat',
  KYC = 'Kyc',
  AUTH = 'Auth',
  REF_REWARD = 'RefReward',
  INFO = 'Info',
  ALL = 'All',
}

export const MailContextTypeMapper: {
  [key in MailContext]: MailContextType;
} = {
  [MailContext.BUY_CRYPTO]: MailContextType.BUY_CRYPTO,
  [MailContext.BUY_CRYPTO_PENDING]: MailContextType.BUY_CRYPTO,
  [MailContext.BUY_CRYPTO_PROCESSING]: MailContextType.BUY_CRYPTO,
  [MailContext.BUY_CRYPTO_CHARGEBACK_UNCONFIRMED]: MailContextType.BUY_CRYPTO,
  [MailContext.BUY_CRYPTO_COMPLETED]: MailContextType.BUY_CRYPTO,
  [MailContext.BUY_CRYPTO_RETURN]: MailContextType.BUY_CRYPTO,
  [MailContext.BUY_FIAT]: MailContextType.BUY_FIAT,
  [MailContext.BUY_FIAT_PENDING]: MailContextType.BUY_FIAT,
  [MailContext.BUY_FIAT_PROCESSING]: MailContextType.BUY_FIAT,
  [MailContext.BUY_FIAT_CHARGEBACK_UNCONFIRMED]: MailContextType.BUY_FIAT,
  [MailContext.BUY_FIAT_COMPLETED]: MailContextType.BUY_FIAT,
  [MailContext.BUY_FIAT_RETURN]: MailContextType.BUY_FIAT,
  [MailContext.CRYPTO_INPUT_RETURN]: MailContextType.BUY_FIAT,
  [MailContext.BLACK_SQUAD]: MailContextType.INFO,
  [MailContext.CHANGED_MAIL]: MailContextType.INFO,
  [MailContext.ADDED_ADDRESS]: MailContextType.INFO,
  [MailContext.ACCOUNT_MERGE_REQUEST]: MailContextType.INFO,
  [MailContext.LIMIT_REQUEST]: MailContextType.INFO,
  [MailContext.CUSTOM]: MailContextType.INFO,
  [MailContext.SUPPORT_MESSAGE]: MailContextType.INFO,
  [MailContext.UNASSIGNED_TX]: MailContextType.INFO,
  [MailContext.LOGIN]: MailContextType.AUTH,
  [MailContext.VERIFICATION_MAIL]: MailContextType.AUTH,
  [MailContext.EMAIL_VERIFICATION]: MailContextType.AUTH,
  [MailContext.KYC_CHANGED]: MailContextType.KYC,
  [MailContext.KYC_FAILED]: MailContextType.KYC,
  [MailContext.KYC_REMINDER]: MailContextType.KYC,
  [MailContext.KYC_PAYMENT_DATA]: MailContextType.KYC,
  [MailContext.REF_REWARD]: MailContextType.REF_REWARD,
  [MailContext.MONITORING]: null,
  [MailContext.WEBHOOK]: null,
  [MailContext.SEPA]: null,
  [MailContext.CHECKOUT_TX]: null,
  [MailContext.DEX]: null,
  [MailContext.PAYOUT]: null,
  [MailContext.PRICING]: null,
  [MailContext.LIQUIDITY_MANAGEMENT]: null,
};
