export const AssetSeed = [
  { name: 'DFI', type: 'Coin', chainId: 0, buyable: true, sellable: false },
  { name: 'dBTC', type: 'DAT', chainId: 2, buyable: true, sellable: false },
  { name: 'dETH', type: 'DAT', chainId: 1, buyable: true, sellable: false },
  { name: 'dBCH', type: 'DAT', chainId: 11, buyable: false, sellable: false },
  { name: 'dDOGE', type: 'DAT', chainId: 7, buyable: false, sellable: false },
  { name: 'dLTC', type: 'DAT', chainId: 9, buyable: false, sellable: false },
  { name: 'dUSDC', type: 'DAT', chainId: 13, buyable: false, sellable: false },
  { name: 'dUSDT', type: 'DAT', chainId: 3, buyable: false, sellable: false },
  { name: 'ETH-DFI', type: 'DAT', chainId: 4, buyable: false, sellable: false },
  { name: 'BCH-DFI', type: 'DAT', chainId: 12, buyable: false, sellable: false },
  { name: 'BTC-DFI', type: 'DAT', chainId: 5, buyable: false, sellable: false },
  { name: 'DOGE-DFI', type: 'DAT', chainId: 8, buyable: false, sellable: false },
  { name: 'LTC-DFI', type: 'DAT', chainId: 10, buyable: false, sellable: false },
  { name: 'USDC-DFI', type: 'DAT', chainId: 14, buyable: false, sellable: false },
  { name: 'USDT-DFI', type: 'DAT', chainId: 6, buyable: false, sellable: false },
];
