export enum GoodsType {
  TANGIBLE = 'Tangible',
  VIRTUAL = 'Virtual',
}

export enum GoodsCategory {
  ELECTRONICS_COMPUTERS = 'ElectronicsComputers',
  BOOKS_MUSIC_MOVIES = 'BooksMusicMovies',
  HOME_GARDEN_TOOLS = 'HomeGardenTools',
  CLOTHES_SHOES_BAGS = 'ClothesShoesBags',
  TOYS_KIDS_BABY = 'ToysKidsBaby',
  AUTOMOTIVE_ACCESSORIES = 'AutomotiveAccessories',
  GAME_RECHARGE = 'GameRecharge',
  ENTERTAINMENT_COLLECTION = 'EntertainmentCollection',
  JEWELRY = 'Jewelry',
  DOMESTIC_SERVICE = 'DomesticService',
  BEAUTY_CARE = 'BeautyCare',
  PHARMACY = 'Pharmacy',
  SPORTS_OUTDOORS = 'SportsOutdoors',
  FOOD_GROCERY_HEALTH_PRODUCTS = 'FoodGroceryHealthProducts',
  PET_SUPPLIES = 'PetSupplies',
  INDUSTRY_SCIENCE = 'IndustryScience',
  OTHERS = 'Others',
}

export enum StoreType {
  ONLINE = 'Online',
  PHYSICAL = 'Physical',
  ONLINE_AND_PHYSICAL = 'OnlineAndPhysical',
}

export enum MerchantCategory {
  ACCOMMODATION_AND_FOOD_SERVICES = 'AccommodationAndFoodServices',
  ADMINISTRATIVE_SUPPORT_WASTE_MANAGEMENT = 'AdministrativeSupportWasteManagement',
  AGRICULTURE_FORESTRY_FISHING_HUNTING = 'AgricultureForestryFishingHunting',
  ARTS_ENTERTAINMENT_RECREATION = 'ArtsEntertainmentRecreation',
  CONSTRUCTION = 'Construction',
  BROKER = 'Broker',
  CRYPTO_ATM = 'CryptoATM',
  CRYPTO_MINING = 'CryptoMining',
  PROPRIETARY_CRYPTO_TRADERS = 'ProprietaryCryptoTraders',
  ALGORITHM_CRYPTO_TRADERS = 'AlgorithmCryptoTraders',
  P2P_MERCHANTS = 'P2PMerchants',
  OTHER_DIGITAL_ASSET_SERVICES_PROVIDER = 'OtherDigitalAssetServicesProvider',
  BANK = 'Bank',
  NON_BANK_FINANCIAL_INSTITUTION = 'NonBankFinancialInstitution',
  MONEY_SERVICES_BUSINESS_PAYMENT_SERVICE_PROVIDERS = 'MoneyServicesBusinessPaymentServiceProviders',
  FAMILY_OFFICE = 'FamilyOffice',
  PERSONAL_INVESTMENT_COMPANIES = 'PersonalInvestmentCompanies',
  SUPERANNUATION_FUND = 'SuperannuationFund',
  SOVEREIGN_WEALTH_FUND = 'SovereignWealthFund',
  INVESTMENT_FUNDS = 'InvestmentFunds',
  EDUCATIONAL_SERVICES = 'EducationalServices',
  BETTING = 'Betting',
  HEALTH_CARE_SOCIAL_ASSISTANCE = 'HealthCareSocialAssistance',
  INFORMATION = 'Information',
  GENERAL_WHOLESALERS = 'GeneralWholesalers',
  MANAGEMENT_OF_COMPANIES_ENTERPRISES = 'ManagementOfCompaniesEnterprises',
  PRECIOUS_STONES_PRECIOUS_METALS_DEALERS = 'PreciousStonesPreciousMetalsDealers',
  CRUDE_OIL_NATURAL_GAS_DEALERS = 'CrudeOilNaturalGasDealers',
  GENERAL_MANUFACTURING = 'GeneralManufacturing',
  MARIJUANA = 'Marijuana',
  MINING_EXTRACTION = 'MiningExtraction',
  PAWN_SHOPS = 'PawnShops',
  PROFESSIONAL_SERVICES = 'ProfessionalServices',
  SCIENTIFIC_TECHNICAL_SERVICES = 'ScientificTechnicalServices',
  PUBLIC_ADMINISTRATION = 'PublicAdministration',
  REAL_ESTATE_RENTAL_LEASING = 'RealEstateRentalLeasing',
  RETAIL_STORES_ELECTRONICS = 'RetailStoresElectronics',
  RETAIL_STORES_FB = 'RetailStoresFB',
  RETAIL_STORES_JEWELRY = 'RetailStoresJewelry',
  RETAIL_TRADE_OTHERS = 'RetailTradeOthers',
  SALE_OF_DRUGS_PHARMACEUTICAL_PRODUCTS = 'SaleOfDrugsPharmaceuticalProducts',
  TOBACCO = 'Tobacco',
  TRANSPORTATION_WAREHOUSING = 'TransportationWarehousing',
  UTILITIES = 'Utilities',
  OTHER_CRYPTO_WEB3_SERVICES = 'OtherCryptoWeb3Services',
  OTHER = 'Other',
}
