version: '3.7'

services:
  btc-node:
    image: kylemanna/bitcoind
    restart: always
    ports:
      - '8000:8332'
    volumes:
      - node-data:/bitcoin/.bitcoin
    command: >
      bitcoind
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcauth=dfx-api:7fcd535abd3eaa2d4d297e8d7dbd818b$2bfec69247f7fccb03c6cf901ddbf987dab9006752a061cfceaeeaae6a158829
      -wallet=dfx-api
      -addresstype=p2sh-segwit
