// AUTH
# @name login
# @prompt signature
POST {{url}}/v1/auth/signIn
content-type: application/json

{
    "address": "{{address}}",
    "signature": "{{signature}}"
}

###

# @prompt signature
POST {{url}}/v1/auth/signUp
content-type: application/json

{
    "address": "{{address}}",
    "signature": "{{signature}}",
    "wallet": "Multisig"
}

###

// USER
@authToken = {{login.response.body.accessToken}}

GET {{url}}/v1/user
Authorization: Bearer {{authToken}}

###

@authToken = {{login.response.body.accessToken}}

POST {{url}}/v1/user/data
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "accountType": "Business",
  "firstName": "string",
  "lastName": "string",
  "phone": "string",
  "address": {
    "street": "string",
    "houseNumber": "string",
    "city": "string",
    "zip": "string",
    "country": {
      "id": 41
    }
  },
  "organizationName": "string",
  "organizationAddress": {
    "street": "string",
    "houseNumber": "string",
    "city": "string",
    "zip": "string",
    "country": {
      "id": 41
    }
  },
  "mail": "string"
}


###

@authToken = {{login.response.body.accessToken}}

PUT {{url}}/v1/user/201879
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "status": "Active"
}

###

@authToken = {{login.response.body.accessToken}}

PUT {{url}}/v1/userData/2202
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "kycLevel": 50
}

###

// ROUTE

@authToken = {{login.response.body.accessToken}}

GET {{url}}/v1/buy
Content-Type: application/json
Authorization: Bearer {{authToken}}



###

// EXCHANGE
GET {{url}}/v1/exchange/binance/balances
Authorization: Bearer {{authToken}}

###

POST {{url}}/v1/exchange/binance/trade
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "from": "BTC",
  "to": "USDT",
  "amount": 0.0222
}

###

GET {{url}}/v1/exchange/trade/705325209
Authorization: Bearer {{authToken}}


###

// BUY CRYPTO
@authToken = {{login.response.body.accessToken}}

POST {{url}}/v1/buyCrypto/53363/webhook
Authorization: Bearer {{authToken}}

###

// BUY FIAT
@authToken = {{login.response.body.accessToken}}

POST {{url}}/v1/buyFiat/57369/webhook
Authorization: Bearer {{authToken}}

###

@authToken = {{login.response.body.accessToken}}

PUT {{url}}/v1/buyCrypto/refVolumes
Authorization: Bearer {{authToken}}

###

@authToken = {{login.response.body.accessToken}}

PUT {{url}}/v1/buyCrypto/volumes?start=20308&end=20309
Authorization: Bearer {{authToken}}

###

// LM
@authToken = {{login.response.body.accessToken}}

POST {{url}}/v1/liquidityManagement/pipeline/buy
content-type: application/json
Authorization: Bearer {{authToken}}

{
  "assetId": 308,
  "minAmount": 100,
  "targetOptimal": false
}

###

@authToken = {{login.response.body.accessToken}}

POST {{url}}/v1/liquidityManagement/pipeline/sell
content-type: application/json
Authorization: Bearer {{authToken}}

{
  "assetId": 290,
  "minAmount": 0.05,
  "targetOptimal": false
}

###

// CRYPTO ROUTE
@authToken = {{login.response.body.accessToken}}

POST {{url}}/v1/cryptoRoute
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "blockchain": "Ethereum",
  "targetAsset": {
    "id": 140
  }
}

###

// DEPOSIT
@authToken = {{login.response.body.accessToken}}

POST {{url}}/v1/deposit
content-type: application/json
Authorization: Bearer {{authToken}}

{
  "blockchain": "Ethereum",
  "count": 1
}

###

@authToken = {{login.response.body.accessToken}}

PUT {{url}}/v1/deposit/lightningWebhook
Content-Type: application/json
Authorization: Bearer {{authToken}}


###


// KYC

GET {{url}}/v2/kyc/contactdata?sequence=0
content-type: application/json
x-kyc-code: ***kyc code***

###

@authToken = {{login.response.body.accessToken}}

POST {{url}}/v1/kyc/admin/webhook
content-type: application/json
Authorization: Bearer {{authToken}}

{
  "userDataId": 207838
}

###

@authToken = {{login.response.body.accessToken}}

POST {{url}}/v1/kyc/admin/ident/file/sync?step=72208
content-type: application/json
Authorization: Bearer {{authToken}}

###



// ALCHEMY

@authToken = {{login.response.body.accessToken}}

POST {{url}}/v1/alchemy/syncTransactions
content-type: application/json
Authorization: Bearer {{authToken}}

{
  "blockchain": "Polygon",
  "fromBlock": 63869127,
  "toBlock": 63869127,
  "address": "0x..."
}

###

// BANK TX

@authToken = {{login.response.body.accessToken}}

POST {{url}}/v1/bankTx
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="file.xml"
Content-Type: application/xml

< ./file.xml
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

// GS

@authToken = {{login.response.body.accessToken}}

POST {{url}}/v1/gs/evm/coinTransaction
content-type: application/json
Authorization: Bearer {{authToken}}

{
  "fromAddress": "0x...",
  "toAddress": "0x...",
  "amount": 0.0449,
  "blockchain": "Arbitrum"
}

###

@authToken = {{login.response.body.accessToken}}

POST {{url}}/v1/gs/evm/tokenTransaction
content-type: application/json
Authorization: Bearer {{authToken}}

{
  "fromAddress": "0x...",
  "toAddress": "0x...",
  "assetId": 124,
  "amount": 82.987437,
  "blockchain": "BinanceSmartChain"
}

###

@authToken = {{login.response.body.accessToken}}

POST {{url}}/v1/gs/evm/bridgeApproval
content-type: application/json
Authorization: Bearer {{authToken}}

{
  "l1AssetId": 251,
  "l2AssetId": 259
}

###

@authToken = {{login.response.body.accessToken}}

POST {{url}}/v1/gs/evm/contractApproval
content-type: application/json
Authorization: Bearer {{authToken}}

{
  "assetId": 265,
  "contractAddress": "0x..."
}

###

// PAYOUT

@authToken = {{login.response.body.accessToken}}

POST {{url}}/v1/payout/speedup?id=36004
Authorization: Bearer {{authToken}}


###

// PRICING

@authToken = {{login.response.body.accessToken}}

PUT {{url}}/v1/pricing
Authorization: Bearer {{authToken}}

###

@authToken = {{login.response.body.accessToken}}

GET {{url}}/v1/pricing?source=Binance&from=LTC&to=USDT
Authorization: Bearer {{authToken}}

###

@authToken = {{login.response.body.accessToken}}

GET {{url}}/v1/pricing/price?fromType=Fiat&fromId=1&toType=Asset&toId=264&allowExpired=false
Authorization: Bearer {{authToken}}


###

// CUSTODY

@authToken = {{login.response.body.accessToken}}

PUT {{url}}/v1/custody/admin/user/324748/balance?assetId=337
Authorization: Bearer {{authToken}}

### 

// PAYMENT

@authToken = {{login.response.body.accessToken}}

POST {{url}}/v1/paymentLink/integration/binance/activate/xxx
Authorization: Bearer {{authToken}}

### 

@authToken = {{login.response.body.accessToken}}

PUT {{url}}/v1/paymentLink/xxx/pos?scoped=false
Authorization: Bearer {{authToken}}

